### ISSUE TITLE
Question: Why do we need express?

### ISSUE THREAD

**Issue by kamthamc** [wikimedia/WikiContrib#1]
I was exploring the repo and found expressJS. Why do we need expressjs when we can use `npm run start` which uses `react-scripts` to run ? Any specific use case?

cc @tuxology

**Comment by rammanoj** [comment]
We need express to host the reactjs app in production. I guess `react-scripts` only work locally. But In production I guess there is a need to use `express` server. As you can see the file [server.js](https://github.com/rammanoj/Contraband/blob/master/frontend/Contraband-Frontend/server.js). It is used for hosting the app in production.

**Comment by kamthamc** [comment]
in prod we don't need express. its just static html, js & css files, can be served through cdn (for eg https://devcenter.heroku.com/articles/fastly)

**Comment by rammanoj** [comment]
Yeah! thanks for the link. I followed a [medium blog](https://medium.com/@maison.moa/setting-up-an-express-backend-server-for-create-react-app-bc7620b20a61), which done the task using express. I will update the repo soon with new requirements.

**Comment by rammanoj** [comment]
removed server.js file

Thanks for the question. Learnt few new things on researching about it.
