### ISSUE TITLE
Can't use FS functions.

### ISSUE THREAD

**Issue by ajuancer** [wikimedia/WikiContrib#101]
Hi!
I'm trying to implement some functions in the activity.js of the Frontend part ([this file)](https://github.com/wikimedia/WikiContrib/blob/master/frontend/WikiContrib-Frontend/src/components/activity.js). I need to make use of the Node.js File System Module, but when I test the changes, I get the TypeError `fs.readFileSync is not a function`. 
The simplify code:
```javascript
myFunction= (variable) => {
    var fs = require('fs');
    if (variable == "this") {
      var path = "file.svg";
      var contents = fs.readFileSync(path, "utf8");
      return contents.toString();
    } else {
      return "Hi!";
    }
  };
```
Thanks in advance.

**Comment by rammanoj** [comment]
As per the answer in this [link](https://stackoverflow.com/questions/43199224/uncaught-typeerror-fs-readfilesync-is-not-a-function-in-console), ``fs`` is a nodejs built-in module, it need server to execute. But the above code is executing in the browser. This is the reason for the error!!

Closing the task, feel free to re-open if you have any more queries...
