### ISSUE TITLE
Make improvements to WikiContrib tool documentation on wikicontrib.readthedocs.io

### ISSUE THREAD

**Issue by NdibeRaymond** [wikimedia/WikiContrib#108]
while going through the wikicontrib documentation on (https://wikicontrib.readthedocs.io),
I noticed certain grammatical errors that might affect how a non-native English speaker is going to understand the documentation. For example:
![IMG_20200308_030612](https://user-images.githubusercontent.com/40905613/76155264-f9093c80-60e9-11ea-9025-1944865d9799.jpg)
![IMG_20200308_030633](https://user-images.githubusercontent.com/40905613/76155265-fa3a6980-60e9-11ea-9755-a42c2a70be40.jpg)

These errors should be corrected as they might affect how a non native English speaker understands the whole document

**Comment by NdibeRaymond** [comment]
I would love to work on this issue

**Comment by MeherChinwala** [comment]
Hi, I'm an Outreachy aspirant, can I work on this issue @srish ? Thanks.

**Comment by srish** [comment]
@NdibeRaymond Hi and welcome! Thanks for reporting this issue, it is a good one :) I see that you commented on some other issues as well, though I haven't gone through all of them yet. My recommendation would be to start from this issue (as it is fairly easy than others to get familiar with the project) and come to others later. Assigning this to you!

**Comment by srish** [comment]
@NdibeRaymond Just noticed that you have already sent a PR! Thanks! I will review it soon.
