### ISSUE TITLE
Make the tool more responsive and mobile friendly

### ISSUE THREAD

**Issue by NdibeRaymond** [wikimedia/WikiContrib#114]
I noticed that this tool wasn't optimized for mobile use.
For example on device with screen width of 360 DIP, the tool looks like this
![IMG_20200309_005712](https://user-images.githubusercontent.com/40905613/76173782-a770b880-61a2-11ea-9f47-fac271fadd4e.jpg)
![IMG_20200309_010857](https://user-images.githubusercontent.com/40905613/76173785-a93a7c00-61a2-11ea-9deb-3f5b1403e6a3.jpg)
![IMG_20200309_010827](https://user-images.githubusercontent.com/40905613/76173786-a9d31280-61a2-11ea-8e2a-845a4c466be4.jpg)

My proposition is to make the tool more mobile friendly

**Comment by NdibeRaymond** [comment]
@srish I would love to take on this issue

**Comment by srish** [comment]
Thanks for your work on this @NdibeRaymond :)
