### ISSUE TITLE
Improve the Accessibility of the tool

### ISSUE THREAD

**Issue by NdibeRaymond** [wikimedia/WikiContrib#115]
running chrome lighthouse audit reveals that the current accessibility rating for the result page is:

![result_page_accessbility_report](https://user-images.githubusercontent.com/40905613/76182225-71dcc700-61c4-11ea-90d1-7c3c67754f41.JPG)

and the current accessibility rating of the home page is:

![wiki_contrib_home_page_accessbility_report](https://user-images.githubusercontent.com/40905613/76182231-74d7b780-61c4-11ea-8500-8402958f35c2.JPG)

 seeing that we are not creating any custom elements, I don't see why WikiContrib shouldn't be hitting a 100% accessibility rating.

**Comment by NdibeRaymond** [comment]
@srish i would love to work on this task

**Comment by srish** [comment]
Thanks a lot @NdibeRaymond :)
