### ISSUE TITLE
[version] `primordials` is not supported with gulp<=3 and node>=12

### ISSUE THREAD

**Issue by muskangupta-iitr** [wikimedia/WikiContrib#121]
During installation I found out a version combination on which `npm install` command will fail and give the following error :

![premordials-error](https://user-images.githubusercontent.com/50856599/76562154-c46ef980-64ca-11ea-8980-2e0f5f548654.png)

## Solution
This error can be solved by either downgrade the node version from 12 or upgrade gulp from 3. So, `README.md` should be updated accordingly with clear instruction for this combination and commands for upgrading gulp or downgrading node.

@srish Can I make a PR with updated documentation?

**Comment by srish** [comment]
@muskangupta-iitr Thanks for reporting this issue, I've noticed this error as well while working on others projects :) It might be good to have this documented in the README.

**Comment by srish** [comment]
Thanks a lot @muskangupta-iitr for this PR :)
