### ISSUE TITLE
[splitting] Code splitting is not implemented in react app

### ISSUE THREAD

**Issue by muskangupta-iitr** [wikimedia/WikiContrib#122]
As the app includes more third party libraries and number of components increased, the bundles size of the app also increase. Bundling in react app will be mostly done by bundler like Webpack, Rollup, Browserify. Code-splitting your app can help you “lazy-load” just the things that are currently needed by the user, which can dramatically improve the performance of your app.

## Solution
We can implement code splitting using `React.lazy()` to lazy load our components. Official documentation for lazy loading and code-splitting => [React Docs](https://reactjs.org/docs/code-splitting.html).

I would like to work on this issue :+1:

**Comment by srish** [comment]
@muskangupta-iitr Correct me if I am wrong, from what I understand this would require changing/re-organizing code in all of the components. Is that true? If so, this might not be a good task for the application round, as a lot of candidates will be working on different bits and pieces of the app, and the project will be in continuous development phase.

**Comment by muskangupta-iitr** [comment]
@srish No, it doesn't change the structure but just change the way to import components. Most of the components are imported in `App.js` file, so changes will be only reflected in that file only.

**Comment by muskangupta-iitr** [comment]
@srish Should I show you the any demo `.js` file for this ?

**Comment by muskangupta-iitr** [comment]
@srish How should I proceed further on this issue as I have already worked on this on my local system. If you allow, I would make a PR and you can review and decide as to what needs to be changed or done with it further.

**Comment by srish** [comment]
@muskangupta-iitr Okay, please send a PR. I will take a look.

**Comment by muskangupta-iitr** [comment]
@srish Done :+1:

**Comment by srish** [comment]
@muskangupta-iitr Thank you for the PR! The changes looked good :)

**Comment by rammanoj** [comment]
Thanks for the change @muskangupta-iitr. I see improvement in results from the PR.
