### ISSUE TITLE
Bug in filter form fields

### ISSUE THREAD

**Issue by NdibeRaymond** [wikimedia/WikiContrib#123]
The "time range" and the "from" fields in the filter form are not functioning properly. I tried selecting the date ranges and found out that sometimes you try clicking on maybe "30 days" and 60 days is selected instead. You try clicking on January and December is selected instead. Sometimes it doesn't move at all and just remains on the previous value it was before you tried selecting another time range.

**Steps To Reproduce**
 * Visit the tool 
 * Search for a contributor (You can use this details: fullname = Bryan Davis, gerrit username 
 =BryanDavis, phab username = bd808)
 * Open the filter
 * go to time range and try selecting the ranges sequentially from 30 days to 1 year, back to 
 30 days

**Expected Result**
The selection should work seamlessly without skipping step or refusing to move

**Comment by NdibeRaymond** [comment]
@srish  I would love to work on this

**Comment by srish** [comment]
@NdibeRaymond I have a feeling that this issue might be related to
https://github.com/wikimedia/WikiContrib/issues/98, https://github.com/wikimedia/WikiContrib/issues/102. So those should be addressed first.

**Comment by NdibeRaymond** [comment]
@srish it seems this issue is not related to #102 as the problem still persists even after #102 has been merged

**Comment by rammanoj** [comment]
Thanks for working on this @NdibeRaymond
