### ISSUE TITLE
Phabricator and Gerrit graphs displaying more contributions than were requested

### ISSUE THREAD

**Issue by NdibeRaymond** [wikimedia/WikiContrib#124]
Phabricator and gerrit graphs are plotting more contributions than they should. This can confuse reviewers and make it seem like someone contributed more than they did.

**Steps To Reproduce**
 * Visit the tool 
 * Search for a contributor (You can use this details: fullname = Bryan Davis, gerrit username 
 =BryanDavis, phab username = bd808)
 * Open the filter, go to "from" field and select February 2020
 * go to "time range" field and select 6 months and apply filter

**Expected outcome**
The graphs as well as the contribution table should show contributions from September 2019 to February 2020

**Actual outcome**
While the contribution table worked correctly, the graphs showed contributions from July August 2019 to march 2020
![IMG_20200312_235538](https://user-images.githubusercontent.com/40905613/76575284-fc703f80-64be-11ea-93a9-b4ee1ba4ed9e.jpg)

![20200312-223321](https://user-images.githubusercontent.com/40905613/76575311-0c881f00-64bf-11ea-8ac9-a3b9befed824.png)
![20200312-235646](https://user-images.githubusercontent.com/40905613/76575313-0e51e280-64bf-11ea-930b-0e8b49db98b0.png)
![20200312-230610](https://user-images.githubusercontent.com/40905613/76575326-13169680-64bf-11ea-8cb4-03bd719b11e7.png)

**Comment by NdibeRaymond** [comment]
@srish  I would love to work on this

**Comment by srish** [comment]
@NdibeRaymond I have a feeling that this might be due to the incorrect implementation of the date range filter. So, some of those open issues should be addressed first.

**Comment by NdibeRaymond** [comment]
@srish it seems this issue is not related to #102 as the problem still persists even after #102 has been merged.
Can this be assigned to me so I can look into it ?

**Comment by NdibeRaymond** [comment]
closing this issue because it was created under the wrong assumption that the behavior observed was an issue. It wasn't
