### ISSUE TITLE
Server Error 500 if csv file contain certain non-English characters

### ISSUE THREAD

**Issue by NdibeRaymond** [wikimedia/WikiContrib#127]
server throwing error 500 if there is any non-English character in csv file.

**example:**
fullname,Phabricator,Gerrit
Michael Große (WMDE),Michael,Michael Große
Jon Harald Søby (WMNO),jhsoby-WMNO,Jon Harald Søby

**To Reproduce**
 * copy the above csv in *example* into a file with a .csv extension and save
 * visit (https://tools.wmflabs.org/wikicontrib/) and try uploading and searching using the bulk add feature

**Expected result**
The search should be successful and we should see the contributions of the names in the uploaded csv file.

**Actual result**
the query page doesn't redirect to result page. If you open network tab and try visiting the last network request made, you get "Server Error 500"

**Note:**
This behaviour only occurs when you try using the csv upload feature. If you search for the non-English name through the form, the search executes successfully

**Comment by NdibeRaymond** [comment]
@srish I would like to attempt solving this issue

**Comment by srish** [comment]
@NdibeRaymond thanks for your work on this! :)
