### ISSUE TITLE
Incomplete installation guide

### ISSUE THREAD

**Issue by NdibeRaymond** [wikimedia/WikiContrib#130]
The installation guide isn't really complete, as it omits to point out how to communicate with your own local Django server instead of the hosted one. Currently, all communications are done with the hosted backend. You can confirm this by looking at the API.js file, the local host URL is commented out but this was not indicated in the installation guide.
Is there any specific reason this was done or is it just a mistake?

**Comment by NdibeRaymond** [comment]
@srish , if this is not deliberate, I can fix it up

**Comment by srish** [comment]
@NdibeRaymond I am not a 100% sure about that implementation. Could you ping @rammanoj and @tuxology in https://wikimedia.zulipchat.com/#narrow/stream/220258-gsoc20-outreachy20/topic/WikiContrib and confirm?

**Comment by NdibeRaymond** [comment]
Ok @srish , I will do that then get back to you when I get a reply

**Comment by srish** [comment]
@NdibeRaymond Thank you for working on this.. while merging it I was wondering though if there should be a mechanism to detect if app is in development or production mode and then we use the `BASE_API_URL` accordingly. What you think? 
(closing this issue for now)

**Comment by NdibeRaymond** [comment]
@srish that's actually very thoughtful. I will file an issue for it

**Comment by rammanoj** [comment]
Thanks for the change @NdibeRaymond and also for finding it. I missed it in the docs unfortunately.
