### ISSUE TITLE
strftime('%s') causing server error on windows

### ISSUE THREAD

**Issue by NdibeRaymond** [wikimedia/WikiContrib#133]
There are several places in the back-end code where "strftime('%s')" was used to obtain epoch time format. This so happens to be a Linux specific implementation as it leads to error on Windows. There are ways to make this very code platform independent so newbies running Windows can be able to fully contribute to this project

**Comment by NdibeRaymond** [comment]
@srish allow me to fix this problem in a way that is platform independent

**Comment by srish** [comment]
@NdibeRaymond I will come to review this PR in a day or so. In the meantime, could you post the error on windows caused by the specific function use.

**Comment by NdibeRaymond** [comment]
on the browser, this is the error:
![strftime_error_browser](https://user-images.githubusercontent.com/40905613/76842266-44ce8b00-683a-11ea-8598-e8ccb83fb86d.JPG)

the command line gives a more detailed error message:
![strftime_error_cmd](https://user-images.githubusercontent.com/40905613/76842318-5dd73c00-683a-11ea-87b1-d2a20a166c54.JPG)

**Comment by srish** [comment]
Thank you @NdibeRaymond for this fix :) This may have fix that complex bug already, I've a feeling, we can check/debug that later.

**Comment by NdibeRaymond** [comment]
@srish I don't think so. On Linux servers (I believe this project is hosted on Linux), the behavior remains unchanged from what it was prior to this PR. This PR deals mainly with any server machine that doesn't support strftime("%s") eg windows, so as to allow contributors running Windows to contribute successfully. So on Linux machines, strftime("%s") is still used, meaning no difference from what it was initially
