### ISSUE TITLE
"TypeError: context is undefined" when searchSuggest.js is used on Wikidata

### ISSUE THREAD

**Issue by AyushShri** [wikimedia/WikiContrib#134]
When i search for something on Wikidata, it shows an error " TypeError:Context is undefined". in the console while loading the page
The Bug happens in https://www.wikidata.org/w/resources/src/mediawiki.searchSuggest/searchSuggest.js
Tested true for both Firfox and chrome.

**Comment by NdibeRaymond** [comment]
I think this is the wrong repo you are creating this issue on @AyushShri 
Maybe you should check (https://github.com/wikimedia/mediawiki)

**Comment by srish** [comment]
(wrong repo for the issue filed; @AyushShri please chat with us on Zulip if you need help in finding the correct repo)
