### ISSUE TITLE
[admin] User model field password is not read-only

### ISSUE THREAD

**Issue by muskangupta-iitr** [wikimedia/WikiContrib#136]
In the user admin model, password field is editable which is not correct as it is already encrypted. It should be ready-only and change password form should be opened when click on change password.

![change-password-field](https://user-images.githubusercontent.com/50856599/76801629-0dd98480-67fc-11ea-9229-3cdbc22b755b.png)

The problem is same for Query model as hash code can be edited from admin panel. Field `hash_code` should be read only as it is randomly generated.

![hash-code-field](https://user-images.githubusercontent.com/50856599/76803747-93f7ca00-6800-11ea-9a64-98c8c4683bb5.png)

@srish I would like to work on this issue. Please assign it to me!

**Comment by rammanoj** [comment]
@muskangupta-iitr I don't think there is any need of this change as the admin pannel can be only accessed by me or @srish. As far as I remember there is only a single admin user currently and there is no need to have more ones. This can be said as out of project scope. 

You can make a PR and prevent changing the query names. But we can even access databases of the app. So, we can even change there. Please try to focus more on how can we improve performance of the project.

**Comment by muskangupta-iitr** [comment]
@rammanoj Yes, you just have to create a admin model and add that field in read_only. Ohk! I will try to improve the performance.
