### ISSUE TITLE
[fails] Error when phab_response is None 

### ISSUE THREAD

**Issue by muskangupta-iitr** [wikimedia/WikiContrib#138]
I have not added my phab_key and try to request a username but got a error. If the `phab_response` is None, then the following error occured:

![check-missing](https://user-images.githubusercontent.com/50856599/76805241-51d08780-6804-11ea-8c67-24dcda03e877.png)

## Steps to reproduce:
1. Remove PHAB_KEY key from `.env` file.
2. Query any random username

## Solution:
If we implement some checks i.e whether `phab_response` is None or not, it will prevent the above error.
@srish I would like to make PR for this issue.

**Comment by srish** [comment]
I don't think we need an explicit check for `PHAB_KEY` It needs to be present in the `.env`. And, if it is not, then one should be getting an error in the same way as it is right now.

I'm closing this issue.
