### ISSUE TITLE
Button functionality not clear

### ISSUE THREAD

**Issue by eeshadutta** [wikimedia/WikiContrib#139]
![hover_labels](https://user-images.githubusercontent.com/32328812/76827973-f4f5c100-6845-11ea-9b23-66b51162a29c.png)

On the main page, there are 3 buttons below the usernames but it doesn't give the functionality of each button. As a first time user, I wasn't sure which button did what.

We could add labels when the mouse is hovered over each of the buttons or make the buttons more descriptive.

**Comment by eeshadutta** [comment]
@srish I would like to work on this!

**Comment by srish** [comment]
@eeshadutta Thank you for working on this :)
