### ISSUE TITLE
[error] FileNotFoundError if upload directory is not there

### ISSUE THREAD

**Issue by muskangupta-iitr** [wikimedia/WikiContrib#142]
I got a error when I added a `.csv` file:
![Screenshot from 2020-03-18 03-59-22](https://user-images.githubusercontent.com/50856599/76907714-f1f1e380-68cc-11ea-8fbe-f2ee11c50508.png)

This error occurs because I have not created the upload directory. After the creation of the directory, it works fine. There requires a condition which checks if upload exists or not. 
```
os.makedirs(os.path.dirname(filename), exist_ok=True)
```

@srish I would like to work on this issue.

**Comment by srish** [comment]
@muskangupta-iitr could you share the exact steps to reproduce this issue? I don't seem to be able to reproduce it on my end.

**Comment by NdibeRaymond** [comment]
This happens when a user forgets to create upload folder in root directory during setup

**Comment by muskangupta-iitr** [comment]
> @muskangupta-iitr could you share the exact steps to reproduce this issue? I don't seem to be able to reproduce it on my end.

@srish When upload directory is not present and user try upload any csv file.

> @srish This happens when a user forgets to create upload folder in root directory during setup. It's django default behavior. I think it's an issue of missing information in the install.md file for backend. New django users needs to be told to create the folder during setup or else uploads won't work

@NdibeRaymond We can update the documentation but I think automation will be good.

**Comment by srish** [comment]
@muskangupta-iitr You can send a PR with the condition check and documentation changes (though I'm trying to find this upload folder in my root, but I can't and upload seems to work fine for me).

**Comment by srish** [comment]
Thank you @muskangupta-iitr :)
