### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by eeshadutta** [wikimedia/WikiContrib#143]
Some of the error messages displayed are not very clear.

For example, when a csv file with a wrong format is uploaded, the error message displayed is - 'CSV file you have uploaded is not in the supported format. Click on the &#9432 to check the format(while uploading it)'
'&#9432' is not understandable by a user. 

@srish I would like to work on this and fix the error messages for more readability.

**Comment by salmabadawy7** [comment]
hello I'm an Outreachy participate and I would like to work on this issue
