### ISSUE TITLE
Month selection column not working properly

### ISSUE THREAD

**Issue by harshika18** [wikimedia/WikiContrib#150]
While using filter, when we select the month from the drop-down, it select the wrong month what we actually selected. In the attached picture I actually select January 2020, but December 2019 is selected.
![wiki2](https://user-images.githubusercontent.com/44746365/77060896-557c2e00-69ff-11ea-9a50-c1262e8cbd5f.png)

**Comment by harshika18** [comment]
I would like to work on this issue.

**Comment by NdibeRaymond** [comment]
This issue is a duplicate of #123

**Comment by srish** [comment]
(closing this as a duplicate of existing issue)
