### ISSUE TITLE
Status of contribution overflowing in mobile-view

### ISSUE THREAD

**Issue by shivanigangadharan** [wikimedia/WikiContrib#163]
The list of activities or contribution of a day is displayed as several cards. Now, the status of the contribution tends to overflow the card in the mobile view, as shown in the image below. 

![image](https://user-images.githubusercontent.com/30795425/77309853-5d9bdc80-6d23-11ea-97c1-609a29cd50b7.png)

**Comment by shivanigangadharan** [comment]
@srish and @rammanoj I have almost fixed this issue, changed the flex-directions to column and gave some margin for mobile view using media query. Here's how it would look:

![image](https://user-images.githubusercontent.com/30795425/77310031-a2277800-6d23-11ea-8935-41bf58274882.png)

Let me know if that looks good, I'll send the pull request immediately. Thanks! :)

**Comment by NdibeRaymond** [comment]
Responsiveness on mobile device was fixed in pr #120 . Open the site on your mobile device. Laptop browser devtool emulator is not enough

**Comment by shivanigangadharan** [comment]
> Responsiveness on mobile device was fixed in pr #120 . Open the site on your mobile device. Laptop browser devtool emulator is not enough
> 
> ![20200323-173527](https://user-images.githubusercontent.com/40905613/77339993-f125db00-6d2c-11ea-9166-0f3203ead4a8.png)
> ![20200323-173520](https://user-images.githubusercontent.com/40905613/77339997-f2ef9e80-6d2c-11ea-833d-e6a548ed8218.png)
> ![20200323-173513](https://user-images.githubusercontent.com/40905613/77340001-f3883500-6d2c-11ea-9cfb-52855a52659d.png)

Oh, I missed this one, my apologies. Thanks for pointing it out @NdibeRaymond , closing this issue.
