### ISSUE TITLE
Increase the width of the activity boxes to align it with the one above

### ISSUE THREAD

**Issue by eeshadutta** [wikimedia/WikiContrib#168]
The appearance of the activity boxes which are displayed when the user clicks on a particular day can be modified. 
![Screenshot from 2020-03-24 23-41-59](https://user-images.githubusercontent.com/32328812/77462014-77274c00-6e29-11ea-9cbe-6fb7f1a9cbfa.png)

1) The heading 'XYZ's activity on date' is in very small font which can be changed.
2) The boxes aren't aligned/centered appropriately. The width of the boxes can be increased.

**Comment by srish** [comment]
Thank you @eeshadutta for your work on this :)
