### ISSUE TITLE
Summary of activity

### ISSUE THREAD

**Issue by eeshadutta** [wikimedia/WikiContrib#169]
While we are displaying graphs for the activity, we could also display some cards giving an overview of the overall activity at a glance, something similar to the top 4 cards in the below dashboard which could display the total contributions to Gerrit and Phabricator for the given time duration. 
![total_activity](https://user-images.githubusercontent.com/32328812/77463065-08e38900-6e2b-11ea-9ca4-2a719d7c3cde.png)

@srish if this a feature which could be added to the tool, could I take it up?

**Comment by eeshadutta** [comment]
@srish Could I work on this?

**Comment by NdibeRaymond** [comment]
@srish and @rammanoj , what are your takes on this issue?

**Comment by srish** [comment]
The WikiContrib tool started with an idea to have something super simple for individual users (as there is Wikimedia Bitergia already, but that is more for Wikimedia community managers/administrators). So, I would be hesitant to add more design elements and features like the one proposed in this task. Closing this task for now.
