### ISSUE TITLE
Backend Error

### ISSUE THREAD

**Issue by jencwong** [wikimedia/WikiContrib#174]
I got this error message when I tried to run the WikiContrib localhost on my browser.

I got to the landing page fine, but when I entered the user's name, Gerrit's account and Phabricators account and clicked search, I got the error message (attached), and the browser kept on trying to load without rendering anything.
![Screen Shot 2020-03-25 at 3 08 21 PM](https://user-images.githubusercontent.com/50587066/77601230-9634e500-6ee0-11ea-85e5-6a5d011370fc.png)

**Comment by NdibeRaymond** [comment]
I'd like to look into this error @srish

**Comment by NdibeRaymond** [comment]
Hey @jencwong , can you share details on how to reproduce this?
Your OS, the usernames you where searching for, etc.
Also, have you tried switching to the master branch (if you are not already on it)?

**Comment by jencwong** [comment]
@NdibeRaymond  I responded to you with a private message.

**Comment by NdibeRaymond** [comment]
Looking at your error trace, one can conclude that the request is returning None for phab related operations. I think this has something to do with your api_key

**Comment by NdibeRaymond** [comment]
Go to your .env file, if the values there is this,
PHAB_KEY=api-xxxxyyyyzzzz
Then you need your own API key. Go to install.md file and follow the instruction there to find out how to get yours

**Comment by srish** [comment]
Thank you @NdibeRaymond for helping @jencwong resolve this issue :)
