### ISSUE TITLE
Add Meta page and Github repo link on the website

### ISSUE THREAD

**Issue by shivanigangadharan** [wikimedia/WikiContrib#176]
The idea is to build a footer for the website. Below are the specifications that I propose:

-  GitHub link of WikiContrib

- Documentation link of WikiContrib

- Link to guidelines for making contributions

We can also have a header or a navigation bar containing different menu options adding to the functionality of the website, but primary focus is the footer for now. 

Any suggestions, design ideas, content or links are very welcome. Thanks! :)

**Comment by shivanigangadharan** [comment]
@srish I would love to work on this if you permit.

**Comment by srish** [comment]
@shivanigangadharan Thanks for filing this. I think that a footer may not look good without the header :) And, the minimal design that we have right now is serving the needs well.

Though what might be helpful is adding a link to the Meta page and Github repository. So, this task could perhaps be about that.

**Comment by shivanigangadharan** [comment]
> @shivanigangadharan Thanks for filing this. I think that a footer may not look good without the header :) And, the minimal design that we have right now is serving the needs well.
> 
> Though what might be helpful is adding a link to the Meta page and Github repository. So, this task could perhaps be about that.

Ahh, got it. Sounds good to me. So what would you suggest, should I add the Meta page and GitHub repo link on a small header on top of the page, or in the hover content of the 'i' icon next to the docs button?

**Comment by NdibeRaymond** [comment]
@srish what is your take on this issue?

**Comment by srish** [comment]
@NdibeRaymond I imagine something like the footer here on https://pageviews.toolforge.org/?project=en.wikipedia.org&platform=all-access&agent=user&redirects=0&range=latest-20&pages=Cat|Dog for WikiContrib. It should be minimalistic, see the last line with FAQ, Report Source, etc. on the link I've shared.

**Comment by NdibeRaymond** [comment]
Visted the link you shared @srish. It is awesome! I now understand what you mean. It would be nice to have something like that. and it is something we can implement during this internship

**Comment by srish** [comment]
@NdibeRaymond We can have two items for now in the footer: View source (linked to code repository on Github) and Discuss (linked to the talk page on meta-wiki).

**Comment by NdibeRaymond** [comment]
> @NdibeRaymond We can have two items for now in the footer: View source (linked to code repository on Github) and Discuss (linked to the talk page on meta-wiki).

Got it @srish
