### ISSUE TITLE
Active tab depending on the topic

### ISSUE THREAD

**Issue by harshika18** [wikimedia/WikiContrib#182]
When you scroll down in the usage doc the active tab should also change based on the topic displayed on the screen. Like the topic displayed on the screen is "Viewing / Updating filters" while the active tab in list of topics in the left of the screen is "Intro to Queries"
![Screenshot from 2020-03-30 02-49-21](https://user-images.githubusercontent.com/44746365/77861326-d7572d00-7231-11ea-9a8b-96e1c0f7a4ff.png)

**Comment by harshika18** [comment]
@srish I would love to take this up

**Comment by NdibeRaymond** [comment]
@srish and @rammanoj , is this like the default behavior of readthedocs.io ?
if it is then I think we need to close this PR as it is not directly related to Wikicontrib code and not something we have under our control
