### ISSUE TITLE
Browser back button doesn't direct to WikiContrib landing page

### ISSUE THREAD

**Issue by pavithraes** [wikimedia/WikiContrib#184]
The browser back button, when clicked from "User's Activity" page doesn't direct to the WikiContrib home page. 

![wikicontrib-screencast](https://user-images.githubusercontent.com/33131404/78009037-108cbb80-735e-11ea-8cb8-83e325c79c77.gif)

**Comment by shivanigangadharan** [comment]
@pavithraes Can I work on this issue, please?

**Comment by rammanoj** [comment]
@pavithraes I guess we can extend this issue. I mean the current issue you report might not solve the issue with back button completely. You can refer https://github.com/wikimedia/WikiContrib/pull/188#issuecomment-619703689

**Comment by pavithraes** [comment]
@rammanoj Yes, extending seems fair. :)

**Comment by NdibeRaymond** [comment]
@rammanoj is it possible that this is a browser-specific problem? I can't seem to reproduce this on my chrome
