### ISSUE TITLE
can't return to result page once you navigate away

### ISSUE THREAD

**Issue by NdibeRaymond** [wikimedia/WikiContrib#190]
**How to Reproduce**
- Visit the tool
- Search for a user's contribution
- copy the query id then navigate away (either with the nav button or to a different domain)
- now try navigating back to the result page

**Expected Result**
It is supposed to be possible to return back to the result page even after you have navigated away

**Actual Result**
You can't get back to the result page again once you navigate away unless you create a new query with the same user details. Even when you manually paste the query id (assuming you copied the query id of the original query), you still can't get back to the original query result page

**Comment by NdibeRaymond** [comment]
@srish I have a reason to believe this is bug that comes with PR #184, because if you comment line 11 of activity.js, this issue no longer occurs. That line was added by PR #184

**Comment by rammanoj** [comment]
If this happens because of that change, lets undo it.

**Comment by NdibeRaymond** [comment]
@rammanoj I think so too. Maybe we undo the commit and check again

**Comment by NdibeRaymond** [comment]
@rammanoj and @srish this is still a problem

**Comment by NdibeRaymond** [comment]
closing this issue now because it has been fixed
