### ISSUE TITLE
CI/CD integration using Travis

### ISSUE THREAD

**Issue by kamthamc** [wikimedia/WikiContrib#2]
Is it possible to use travis-ci to build, version and deploy to heroku? It would be much easier to see config and builds.

cc @tuxology

**Comment by tuxology** [comment]
@kamthamc I think the final place to host this would be Toolforge (https://tools.wmflabs.org/). We can probably still use Travis to host it there. We will explore this after the first development phase completes.

**Comment by rammanoj** [comment]
Thanks for reporting @kamthamc. Written few tests in python today. will try to complete the all the tests and add the travis CI soon.

**Comment by NdibeRaymond** [comment]
@srish it seems like this issue has been fixed. Maybe we should flag it as closed

**Comment by srish** [comment]
Thanks for your commend @NdibeRaymond!
