### ISSUE TITLE
Disable the list view feature

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#204]
I think that the list view feature will be expensive going forward with integrations such as Github. I think that the list view feature adds complexity is many ways, and that the WikiContrib tool should first try to get attention from users individually. If there is a strong need identified to view contributions of a list of users at once, this feature can be brought back. We don't need to obliterate it from our codebase, disable it on the front end-hovering over on "bulk add" can ask a user to contact the developers to learn more about it.

**Comment by NdibeRaymond** [comment]
@srish , this is very thoughtful. @rammanoj how do you propose we handle this? should we create a PR that removes everything about this feature (we can always pull from an older branch that contains this feature if we later need to reimplement this) or should we create a PR that only disables it on the frontend but still leave the code on the backend (bearing in mind that this might cause confusion for newer contributors)?

**Comment by srish** [comment]
I think we should leave code as it is, and perhaps remove disable the "bulk add" button and comment the code that displays the user button for now. What say? And, then hovering on "bulk add" should give a message like: "this feature is currently disabled. if you want to know more about it, contact the devs."
