### ISSUE TITLE
User name input fields don't have labels

### ISSUE THREAD

**Issue by thiemowmde** [wikimedia/WikiContrib#232]
After clicking the edit button, this is what I get:

![Screenshot from 2020-08-12 09-41-42](https://user-images.githubusercontent.com/6576639/89991021-821d3480-dc83-11ea-9929-ffdfeec3c8b4.png)

Notice there is nothing that tells me what the four input fields mean. 😢

More in-depth explanation of the issue: https://www.nngroup.com/articles/form-design-placeholders/

**Comment by NdibeRaymond** [comment]
Thanks for this @thiemowmde . @srish and @rammanoj , what do you think about this?
