### ISSUE TITLE
Contributions are listed twice

### ISSUE THREAD

**Issue by thiemowmde** [wikimedia/WikiContrib#233]
When I click any of the little green boxes in the "total contributions" chart, I get a list of these contributions, but everything shows up twice. Example:

![Screenshot from 2020-08-12 10-49-52](https://user-images.githubusercontent.com/6576639/89995558-e9d67e00-dc89-11ea-88a0-ec6bba9a16b1.png)

**Comment by NdibeRaymond** [comment]
looking into this @thiemowmde. thanks for reporting
