### ISSUE TITLE
Confusing filter button behavior

### ISSUE THREAD

**Issue by thiemowmde** [wikimedia/WikiContrib#234]
There are 2 buttons, a red magnifying glass and a blue arrow that looks like it is meant as a "reaload" feature:

![Screenshot from 2020-08-12 10-54-24](https://user-images.githubusercontent.com/6576639/89995757-38841800-dc8a-11ea-930d-cf835c5d6ce9.png)

First, it's impossible to tell what these buttons do, because they don't have any label or tooltip title.

When playing around with the buttons, it seems the magnifying glass acts as a "reset" button. It always resets the two input fields above back to "August, 2020" and "Last 1 year", and reloads the graphs. What looks like a "reload" buttons seems to act as a "OK", "Accept changes" or "Apply filter".

Are the two buttons accidentally swapped?

**Comment by NdibeRaymond** [comment]
Thanks for this awesome catch @thiemowmde , submitting a fix now
