### ISSUE TITLE
The 1 year time axis does not change with the filter

### ISSUE THREAD

**Issue by thiemowmde** [wikimedia/WikiContrib#235]
By default, I get a graph like this:
![Screenshot from 2020-08-12 10-59-37](https://user-images.githubusercontent.com/6576639/89996354-fad3bf00-dc8a-11ea-88d1-19765df8b45a.png)

When I open the filters and change the time range to the "Last 60 days", for example, the graph changes like this:
![Screenshot from 2020-08-12 10-59-50](https://user-images.githubusercontent.com/6576639/89996351-f9a29200-dc8a-11ea-8641-5e1a58e9e245.png)

The data is reloaded and the graph redrawn, but the time range shown is still 1 year. The min and max values of the axis are not set to reflect my new filter selection.

**Comment by NdibeRaymond** [comment]
thanks for the observation @thiemowmde . Because this is a design decision, I would like to hear what @rammanoj has to say about this

**Comment by thiemowmde** [comment]
Hm. I experience this behavior as bogus. The graph is cut off, as if I have no contributions before. That's not correct.

To approach it from another perspective: What's the benefit of picking a range? The only positive effect is that it loads faster. But the graph doesn't become better. It doesn't zoom in. I can't see more details.

**Comment by NdibeRaymond** [comment]
> Hm. I experience this behavior as bogus. The graph is cut off, as if I have no contributions before. That's not correct.
> 
> To approach it from another perspective: What's the benefit of picking a range? The only positive effect is that it loads faster. But the graph doesn't become better. It doesn't zoom in. I can't see more details.

You are right @thiemowmde . I think it is still important to hear what others have to say

**Comment by rammanoj** [comment]
That's a intresting question @thiemowmde , thanks for asking. @NdibeRaymond I guess it is true. Can you check if we can alter the timeline even on the graphs based upon the filters that we providing ?
