### ISSUE TITLE
How the "From" filter option is labeled

### ISSUE THREAD

**Issue by thiemowmde** [wikimedia/WikiContrib#236]
The filter says "From", but it looks like it behaves more like a "To". When I pick "June, 2020", the graph stops there and shows everything **before**. An alternative label might be "Until".

**Comment by NdibeRaymond** [comment]
@rammanoj and @srish , what do you think about this?

**Comment by srish** [comment]
@thiemowmde that's a great point! thanks! 

@NdibeRaymond How about we swap the combo boxes and also modify the labels accordingly? (see screenshot):

<img width="806" alt="Screen Shot 2020-08-13 at 12 35 05 PM" src="https://user-images.githubusercontent.com/288353/90178886-7acc5880-dd61-11ea-90ec-909060b1129c.png">

**Comment by NdibeRaymond** [comment]
> @thiemowmde that's a great point! thanks!
> 
> @NdibeRaymond How about we swap the combo boxes and also modify the labels accordingly? (see screenshot):
> 
> <img alt="Screen Shot 2020-08-13 at 12 35 05 PM" width="806" src="https://user-images.githubusercontent.com/288353/90178886-7acc5880-dd61-11ea-90ec-909060b1129c.png">

This is a perfect fit!
