### ISSUE TITLE
Contributions counted twice because of GitHub mirrors

### ISSUE THREAD

**Issue by thiemowmde** [wikimedia/WikiContrib#237]
As far as I'm aware of most, if not all Gerrit code repositories are mirrored on GitHib. It looks like these mirrored contributions are all included in the graphs. Here is an example:

![Screenshot from 2020-08-12 11-09-05](https://user-images.githubusercontent.com/6576639/89997320-46d33380-dc8c-11ea-8f76-a047e302b05d.png)

That's the same contribution. The second one is the GitHub mirror.

I'm not exactly sure what to do about this. It might be possible to use the Git commit IDs to filter these duplicates.

**Comment by NdibeRaymond** [comment]
looking into this @thiemowmde . Thanks for reporting
