### ISSUE TITLE
Host the tool at https://tools.wmflabs.org/wikicontrib/

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#24]
Currently, there is no way to rename the tool in Wikimedia Toolforge. This might sound painful, but to host the tool here: https://tools.wmflabs.org/wikicontrib/, the entire process followed to here https://tools.wmflabs.org/contrabandapp/ would need to be repeated.

**Comment by rammanoj** [comment]
Thanks @srish, the app is now hosted at https://tools.wmflabs.org/wikicontrib/. I will make a commit with an markdown file (describing how to host the app on toolforge) soon.
