### ISSUE TITLE
Years in date range are a bit confusing (the order is backwards?)

### ISSUE THREAD

**Issue by mooeypoo** [wikimedia/WikiContrib#27]
This is an awesome tool, thank you for working on this!

I think I found a weird bug (unless I'm missing something?) with how the dates and ranges are displayed.

I looked for my contributions, and I got this:
![datebug](https://user-images.githubusercontent.com/261238/64311153-dab65e80-cf57-11e9-942f-fbd0f2f0e12b.png)

The date boxes at the bottom with the contributions also seem to go left-to-right from September 2019 (today) to August 2018 (last year) which is a bit odd for a direction.

Shouldn't the dates go from August 2018 to September 2019? 

Also, somewhat relatedly, the Phab/Gerrit count displays months Jan to Dec, which is not the same range that is displayed above (Aug-September) 
![yearrange](https://user-images.githubusercontent.com/261238/64311266-4ef10200-cf58-11e9-8898-2cc11e64785f.png)

I think there might be a bit of a mismatch of the output of the labels vs the actual calculation?

**Comment by srish** [comment]
Addressed here https://github.com/wikimedia/WikiContrib/pull/39. Closing this issue :) Thank you @mooeypoo for reporting it <3
