### ISSUE TITLE
Y-axis should have integer values only

### ISSUE THREAD

**Issue by Jain-Aditya** [wikimedia/WikiContrib#28]
The tool looks really great! I have a small suggestion. On the activity page, the y-axis values on the graphs should be integer only because showing the fractional values does not make sense over here. Perhaps, you can use something like:
https://github.com/WikipediaLibrary/hashtags/blob/master/hashtagsv2/hashtags/static/js/graph.js#L33

There might also be other ways of doing this :)

**Comment by Jain-Aditya** [comment]
I think, the issue has already been fixed by adding the configuration option `stepSize`
https://github.com/wikimedia/WikiContrib/blob/8e9f74747751c7a098b94ae9b0c0407c1a0d5b58/frontend/WikiContrib-Frontend/src/result.js#L59

**Comment by srish** [comment]
Thank you @Jain-Aditya for filing this issue :)
