### ISSUE TITLE
Hide Gerrit statistics when not needed

### ISSUE THREAD

**Issue by Jain-Aditya** [wikimedia/WikiContrib#29]
One enhancement worth having could be to not display/hide the Gerrit statistics graph when Gerrit username is not specified in the query. Same could be done for phabricator stats.

**Comment by rammanoj** [comment]
@Jain-Aditya This is a good feature but this affects UI a lot!! 

If no graph is displayed, it creates a lot of space over there, it might not look appealing for the users of the tool. The UI need a tweak a bit in that case. It will be good if you can suggest an alternate UI!

**Comment by Jain-Aditya** [comment]
Ah yes @rammanoj ! - One option is to simply increase the size of the other chart to fill up the empty space. What do you think?

**Comment by NdibeRaymond** [comment]
I would love to work on this issue @rammanoj  but I would need certain pointers like for example if I should remove the chart and leave the space blank or if I should remove it and increase the other chart to fill up the given space

**Comment by srish** [comment]
(closing this issue for now, I think this is going to affect the UI)
