### ISSUE TITLE
Dockerize app for local build and run

### ISSUE THREAD

**Issue by kamthamc** [wikimedia/WikiContrib#3]
Is it possible to create a docker config to run the application locally along with elastic search, caching service etc?

cc @tuxology

**Comment by codeEmpress1** [comment]
Hi @kamthamc , @tuxology, I am an outreachy applicant I would like to work on this issue.

**Comment by abbasidaniyal** [comment]
I would like to take up this issue. @srish

**Comment by srish** [comment]
Thanks a lot @abbasidaniyal for your work on this task and @kamthamc for proposing this idea :)
