### ISSUE TITLE
Compilation fails due to "module not found" error

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#33]
While setting up the `frontend` dev environment, here is the error I ran into: 

<img width="943" alt="Screen Shot 2019-09-14 at 12 21 07 AM" src="https://user-images.githubusercontent.com/288353/64904903-b825f300-d685-11e9-8afb-2a1ceb610d80.png">

I think this is happening because the app is loading the modules for the condition when the `production` variable is `true`, even though the production variable value in `index.js` is set as `false`. This might be due to the fact the build process is completed much before the production variable gets its value.

**Comment by srish** [comment]
@rammanoj @tuxology for one of you to review! :)

**Comment by rammanoj** [comment]
I guess there is no need of ```production``` variable anymore. It can be replaced by ```process.env.NODE_ENV```. I opened #35
