### ISSUE TITLE
Gerrit contributions are not plotted on the "Total Contributions" graph when Phabricator username is not provided

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#40]
If I provide my full name and Gerrit username and leave the Phabricator field empty, my gerrit contributions are not shown in the "Total Contributions" graph, but the Gerrit graph says that there are two contributions. Maybe the problem here is different.

I wonder how the calculations are being calculated. If I look at my Gerrit commits from September 2018, there is only one merged commit made via `srishakatux` and another one with `SrishtiSethi` account:
https://gerrit.wikimedia.org/r/#/q/owner:Srishakatux+status:merged
https://gerrit.wikimedia.org/r/#/q/owner:SrishtiSethi+status:merged.

<img width="969" alt="Screen Shot 2019-09-26 at 8 56 20 PM" src="https://user-images.githubusercontent.com/288353/65747473-579baa80-e0b6-11e9-901c-f1f88cb8f5d1.png">

**Comment by rammanoj** [comment]
@srish Can you reproduce the issue even now ?

In my localhost it displays something like:
![image](https://user-images.githubusercontent.com/21082378/66823010-f3f0f880-ef62-11e9-90e1-99548203b85f.png)

I tried this out and it is showing two contributions in September (2019). The tool counts the dates according to the first patch set sent to the commit. It does not count according to the ```last updated``` time in gerrit.

I used this link: https://tools.wmflabs.org/wikicontrib/Rqj6UdCBjBx93IUFDy8RC7M2vIUkgmUkOpu2NPDOKQQLUptPwFS9H2N31vIglctT

If you stil reproduce the issue can you message here about the steps to reproduce that?

**Comment by srish** [comment]
@rammanoj I just tested this issue in production again and I don't seem to reproduce this. Maybe I was expecting contributions that were not in the time range :-/ I'm closing this for now, we can re-open if necessary.
