### ISSUE TITLE
Fix incorrect installation guide links in README

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#42]
Some links like
https://github.com/rammanoj/WikiContrib/blob/master/backend/Contraband/Install.md needs to be changed as this repo is under `Wikimedia` account now :)

**Comment by gagandeepp** [comment]
@srish  Can you please assign this to me?
And add a label workinprogress to this issue?

**Comment by srish** [comment]
Thanks @gagandeepp for your interest :) Assigning this task to you now..

**Comment by rammanoj** [comment]
@srish and @gagandeepp I guess the frontend link also need to be updated!

**Comment by srish** [comment]
Addressed here https://github.com/wikimedia/WikiContrib/pull/44. Thank you @gagandeepp :)
