### ISSUE TITLE
Y-axis should not display negative labels

### ISSUE THREAD

**Issue by Jain-Aditya** [wikimedia/WikiContrib#45]
Y-axis labels on the graphs should be non-negative integers only. The issue can be reproduced by simply not entering the Gerrit user name and making a search.
![Screen Shot 2019-10-04 at 10 47 44 AM](https://user-images.githubusercontent.com/34097318/66182939-83a9c380-e694-11e9-8cfa-693575eaa903.png)
Potential solution for this could be to set `beginAtZero` to true in chart options. You can see this for reference: https://github.com/WikipediaLibrary/hashtags/blob/master/hashtagsv2/hashtags/static/js/graph.js#L32

**Comment by srish** [comment]
Also related to https://github.com/wikimedia/WikiContrib/issues/29.
