### ISSUE TITLE
Graph labels overlap when contributions are high

### ISSUE THREAD

**Issue by Jain-Aditya** [wikimedia/WikiContrib#46]
Not able to see contributions clearly, when the values are large. This is probably happening because we are setting `stepSize:1` in the chart options and that's why the chart is explicitly showing all Y-axis values starting from 1.

https://github.com/wikimedia/WikiContrib/blob/master/frontend/WikiContrib-Frontend/src/result.js#L59

![Screen Shot 2019-10-04 at 11 15 09 AM](https://user-images.githubusercontent.com/34097318/66184480-dfc31680-e699-11e9-8fe4-84807b7947e9.png)

**Comment by Jain-Aditya** [comment]
You can simply use these Y-axis chart options only and it would be good to go:
https://github.com/WikipediaLibrary/hashtags/blob/master/hashtagsv2/hashtags/static/js/graph.js#L30

**Comment by srish** [comment]
Thanks @Jain-Aditya for filing the issue :)

**Comment by srish** [comment]
With recent changes, we've some improvements to graph formatting now. Thank you @Jain-Aditya :) 
 
AFTER:
<img width="999" alt="Screen Shot 2019-10-05 at 9 19 44 AM" src="https://user-images.githubusercontent.com/288353/66257759-df865200-e751-11e9-80c2-c2431609b10c.png">
BEFORE:
<img width="976" alt="Screen Shot 2019-10-05 at 9 19 50 AM" src="https://user-images.githubusercontent.com/288353/66257760-df865200-e751-11e9-8e48-0b2771e4c237.png">

**Comment by rammanoj** [comment]
@Jain-Aditya Thankyou for your intrest and valuable contributions. The tool has been updated and all the changes you made are now online.
