### ISSUE TITLE
Full Name field left blank on the main page results in server loading forever

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#49]
Message from console:
<img width="525" alt="Screen Shot 2019-10-05 at 9 34 06 AM" src="https://user-images.githubusercontent.com/288353/66257887-55d78400-e753-11e9-81f4-c15bbdb75162.png">

I am guessing that the search query is not dependent on the Full Name. If so, the Full Name field should be optional, and we let a user proceed if they haven't filled it out.

**Comment by ggangix** [comment]
I would like to solve this issue.

**Comment by srish** [comment]
@ggangix thanks for your interest, I've assigned the issue to you :)

**Comment by ggangix** [comment]
Looks like the Full Name is a required field, could we show an error message to the user or if the user doesn't fill the field we can use one of the other two fields as a full name. 

What do you think @srish ?

**Comment by srish** [comment]
@ggangix I think the first part could be to investigate if we require a full name in any of the queries. My sense is not, but maybe just double check on that. 
If we really need a full name, then showing an error would make sense; if not, then just like when a user does not provide `Gerrit` username, and we let them proceed, in a similar way here as well, we keep the same flow.

**Comment by rammanoj** [comment]
@srish and @ggangix fullname is the required field. The main search input searches for the full name. This [API](https://documenter.getpostman.com/view/6222710/SVYurxMj?version=latest#66c574a3-1567-4692-9e85-66ce1f8ef62b) is used to search the users. It require fullname as a parameter.

I guess showing an error when full name is not provided would be fine.

**Comment by srish** [comment]
(addressed here https://github.com/wikimedia/WikiContrib/pull/62)
