### ISSUE TITLE
Changes not reflected in live tool

### ISSUE THREAD

**Issue by Jain-Aditya** [wikimedia/WikiContrib#55]
After merging #47, the graph formatting should've improved. I think the changes aren't pulled into production environment

**Comment by srish** [comment]
@Jain-Aditya Yes, that's right! Currently, our app deployment is set up in a complicated manner. It is not super easy to update the app with changes frequently, and we would prefer to roll out features slowly :) 

I'm closing this task now, there might be another one coming soon related to app deployment.

**Comment by rammanoj** [comment]
The issue #2 is to automate the deployment.
