### ISSUE TITLE
Frontend and backend should be one tool in Toolforge

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#57]
Currently, there are three tools in Toolforge that are related to WikiContrib: 
https://tools.wmflabs.org/wikicontrib/
https://tools.wmflabs.org/contraband/
https://tools.wmflabs.org/contrabandapp

One of these tools host frontend and one of them the backend of the app. I am not sure what the third tool does. I think not only this makes the deployment process complicated but also it means leveraging of unnecessary resources on Toolforge. Ideally, the frontend and backend should be hosted via the same tool in Toolforge. We can then shutdown the other two tools and request for its deletion.

**Comment by MeherChinwala** [comment]
Hi, @srish, is this issue still open?

**Comment by srish** [comment]
(closing this issue for now, will re-open when the need arises)
