### ISSUE TITLE
Replace `contraband` with `wikicontrib` in the codebase

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#59]
The old name of the WikiContrib project is Contraband. Currently, in quite a few places in the codebase, we are still using the old name of the project. For example, for folder names (e.g. backend/Contraband/contraband), module names, documentation, etc. Ideally, `Contraband` gets replaced with `WikiContrib`. 

This task is reserved for Google Code-in students.

**Comment by urbanecm** [comment]
Unchecked "is beginner" (it's comparable with lint error fixing, which isn't usually marked as a beginner task), decreased time available to 4 days and published. See https://codein.withgoogle.com/dashboard/tasks/5728948382597120/.

**Comment by srish** [comment]
Thanks to @n3rsti for working on this issue :)
