### ISSUE TITLE
Count meaningful contributions only

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#60]
Currently, for Gerrit, we are counting all the patches that have a status which matches with the one in the list below: 

```
gerrit_status = [
  'merged',
  'abandoned',
  'closed',
  'pending',
  'reviewed',
];
```
For Gerrit, I think only `merged` contributions are meaningful. Just like in Github, contributions that are under review or not yet merged are not counted. So, ideally, we count only patches with `merged` status.

Currently, for Phabricator, we are counting all those tasks that have a status which matches with the one in the list below: 

```
phab_status = [
  'declined', 
  'resolved', 
  'stalled', 
  'invalid', 
  ‘open’
];
```

For Phabricator, ideally we ignore `invalid` tasks. Maybe we should also ignore `declined` and `stalled` tasks.

**Comment by JanStevcik** [comment]
Hi, if I understand right, you merge data from phabricator and gerit. Now, for Phabricator you want to select data with status: 'open' and 'resolved' and for Gerrit with status 'merged'. ...just for sure.
Please fix me if i'm wrong. 

I would like to do this issue.

**Comment by rammanoj** [comment]
@JanStevcik thanks for your interest, @srish means that. You are welcomed to solve this :)

**Comment by jencwong** [comment]
I would like to work on this issue.

**Comment by srish** [comment]
@jencwong hi and welcome! if you have any questions feel free to reach out in the chat: https://wikimedia.zulipchat.com/#narrow/stream/220258-gsoc20-outreachy20/topic/WikiContrib

**Comment by NdibeRaymond** [comment]
@srish if no one is working on this issue I would love to take it up

**Comment by jencwong** [comment]
> @srish if no one is working on this issue I would love to take it up

Hi @NdibeRaymond  I am working on it  :)

**Comment by eeshadutta** [comment]
Hi @jencwong are you working on this? If not, could I please take it up @srish ?
Thanks

**Comment by jencwong** [comment]
> Hi @jencwong are you working on this? If not, could I please take it up @srish ?
> Thanks

@eeshadutta yes I am. I will make a pr request soon.

**Comment by jencwong** [comment]
@srish I made a PR to address this issue.

**Comment by jencwong** [comment]
@srish Thank you for approving the PR.  Since the PR is closed, is there anything else related to this issue that is still open?  Thank you!
