### ISSUE TITLE
Remove the `contribution status` filter

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#61]
Once the following issue https://github.com/wikimedia/WikiContrib/issues/60 is addressed, maybe we should consider removing the `contribution status` filter. 

I think that the filter is adding complexity and we should keep visualization feature simple. Also, it is of little value for user to apply filter to view contributions that are not meaningful. 

This could also be a Google Code-in task.

<img width="1020" alt="Screen Shot 2019-10-23 at 5 58 53 PM" src="https://user-images.githubusercontent.com/288353/67444646-cd643a80-f5be-11e9-83b4-2abd7bae1e94.png">

**Comment by JanStevcik** [comment]
Hi do you want to hide Contribution status like on screenshot below? 

![scr1](https://user-images.githubusercontent.com/42576360/67523565-3c20c100-f6af-11e9-9eaa-35392c2343cd.png)

I can hide it in css, and if you change your mind, it can be easily getting back.

**Comment by rammanoj** [comment]
Nope, it's not only just hiding the contribution filter, you should also remove all the functions and operations defined for that contribution filter. 

Apart of the front-end, you also need to change the backend i.e the API.

**Comment by srish** [comment]
In addition to what @rammanoj said, we have this task reserved for Google Code-in :)

**Comment by yaeluria** [comment]
Hi, I'm an Outreachy applicant. Can I work on this issue?

**Comment by srish** [comment]
@yaeluria hi and welcome! if you have any questions feel free to reach out in the chat: https://wikimedia.zulipchat.com/#narrow/stream/220258-gsoc20-outreachy20/topic/WikiContrib

**Comment by MeherChinwala** [comment]
Hi, @srish, I'm an outreachy aspirant, where can I find more unassigned issues with a good first issue label? Are more issues going to be added for this project? Thanks.

**Comment by srish** [comment]
@MeherChinwala All the current issues are filed already on Github. You are welcome to set up this project, and create new issues as and when you discover them :) We can then chat more on their feasibility.

**Comment by MeherChinwala** [comment]
@srish, okay thank you! I'll do that.

**Comment by NdibeRaymond** [comment]
@srish if no one is working on this task I would love to take it up as well

**Comment by yaeluria** [comment]
> @srish if no one is working on this task I would love to take it up as well

I've already started work on this.

**Comment by srish** [comment]
Thanks a lot @yaeluria for working in this! :)

**Comment by yaeluria** [comment]
hey @srish, I haven't finished the backend part of this issue yet. Perhaps it's better to leave it open for now.

**Comment by yaeluria** [comment]
Actually, I'd need the changes from issue #60 before I can finish working on the backend so I'll wait first until they are pushed and merged.

**Comment by Simran180** [comment]
hey, can I work on this issue if anyone is not working on it right now?
