### ISSUE TITLE
Modify error message for missing user information

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#66]
> **NOTE:** This task is reserved for Google Code-in students. Please do not claim this task. 

Change the following error message in the code "Please provide the data regarding users." to "To visualize contributions, please provide user(s) information above." If you try to search for a user without providing any information in the input field, you get this error. 

<img width="1047" alt="Screen Shot 2019-11-21 at 11 57 30 AM" src="https://user-images.githubusercontent.com/288353/69372230-2377dc80-0c56-11ea-81cd-8f061957ec8d.png">

**Comment by srish** [comment]
Imported here https://codein.withgoogle.com/dashboard/tasks/5737504729202688/

**Comment by urbanecm** [comment]
Note: As a potentional student, I would ask myself "how to get that error message?" Maybe you can add that information :-).

**Comment by srish** [comment]
@urbanecm Thank you! I've updated the task description both here and on GCI site. Help publish it :)

**Comment by urbanecm** [comment]
Thanks, published!
