### ISSUE TITLE
Modify information about the WikiContrib tool

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#67]
> **NOTE:** This task is reserved for Google Code-in students. Please do not claim this task. 

Replace the message in the information dialog below with "WikiContrib tool provides a visualization within a specified time range of users' contributions to Wikimedia projects on Phabricator and Gerrit."

<img width="283" alt="Screen Shot 2019-11-20 at 5 53 10 PM" src="https://user-images.githubusercontent.com/288353/69293745-aea59380-0bbe-11ea-89af-5e61ce4a7ca4.png">

**Comment by srish** [comment]
Imported here https://codein.withgoogle.com/dashboard/tasks/4984820703166464/.

**Comment by rammanoj** [comment]
@minhducsun2002 Thanks for the update. Your change is live at https://tools.wmflabs.org/wikicontrib
