### ISSUE TITLE
Make improvements to WikiContrib tool documentation on meta wiki

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#68]
Documentation here is outdated: https://meta.wikimedia.org/wiki/WikiContrib. It has a lot of process documentation such as technical implementation, wireframes, and mockups, that may not be useful to a potential user of the tool. 

Some ideas for improving the documentation:
* Move all the implementation details (background info, technical implementation, wireframes, etc.) to a subpage. 
* Proposed workflow can be adjusted slightly to highlight more how the tool works in its current shape and form. Tool screenshots would be a nice addition! 
* "Your feedback on the proposed workflow.. " message in the notice can be modified to invite feedback from users on the workings of the tool.
* Overall, I think the documentation can be re-written to cover the following sections/points:
** What the tool does?
** Who it is for? 
** How it works? 
** How to contribute? Repository link, etc.
** Contact
** See also (could be linked to the subpage with background info, technical details, etc.)

For inspiration look into existing documentation of tools on meta wiki :) Some examples:
* https://meta.wikimedia.org/wiki/Citation_Hunt
* https://meta.wikimedia.org/wiki/Programs_%26_Events_Dashboard

In the process of trying out of the tool, if you encounter any bug, feel free to file an issue in this repository!

**Comment by srish** [comment]
Imported here https://codein.withgoogle.com/dashboard/tasks/5276992933462016/.

**Comment by firshta2016** [comment]
Hi, I am an Outreachy intern and I would love to work on this issue.

**Comment by srish** [comment]
@firshta2016 hi and welcome! if you have any questions feel free to reach out in the chat: https://wikimedia.zulipchat.com/#narrow/stream/220258-gsoc20-outreachy20/topic/WikiContrib

**Comment by firshta2016** [comment]
@srish I am a little lost, do I have to write the content or just basically reorganize the page based on your suggestions above?

**Comment by srish** [comment]
@firshta2016 Hi! This is about re-writing the content on that page. What you see in that page was written at the time the tool was being developed. So, it has more information related to technical implementation right now and less how to use the tool. See the 4th bullet point in the task description which gives some idea what the documentation should cover.

**Comment by eeshadutta** [comment]
Hi @srish Can I take this up? 

Couple of doubts -
Should I be making changes to the page directly by going to [edit] or should I create a document highlighting what changes I would like to make and then edit the main web page if the document seems fine?

Thanks!

**Comment by srish** [comment]
@eeshadutta You can write something in your Sandbox first (it should be a subpage of your user page on meta-wiki). For example https://meta.wikimedia.org/wiki/User:SSethi_(WMF)/Sandbox (mine is empty though right now).
When you are done, I can review and, when satisfied, move over the changes to the main page.

**Comment by eeshadutta** [comment]
Sure @srish I shall do that and let you know once I have substantial work ready.

**Comment by eeshadutta** [comment]
Hi @srish I have written some documentation in my sandbox - https://meta.wikimedia.org/wiki/User:Eeshadutta/Sandbox 
Please could you review it and let me know if any changes are needed. 

PS: I wasn't able to upload images. I was getting the following error. This is a screenshot from the tool (similar to the one on the README in this repository)
![Error](https://user-images.githubusercontent.com/32328812/76974995-ee576e80-6957-11ea-89cc-bb1c188b32aa.jpeg)
Could you please help me how to resolve this?

Thanks!

**Comment by srish** [comment]
@eeshadutta I've made some copyedits in your Sandbox. Here are a few items that are remaining I think:
> * Move all the implementation details (background info, technical implementation, wireframes, etc.) to a subpage.
> * Tool screenshots (in Using the Tool section) would be a nice addition!
> * See also (could be linked to the subpage with background info, technical details, etc.)

I'm not sure why you receiving the error while trying to upload the image/screenshot. What is main.jpeg? Did you download it from somewhere or is it the image/screenshot you took? Also, maybe try to upload it first on Wikimedia Commons and read some guidelines here first to do so: https://commons.wikimedia.org/wiki/Commons:First_steps/Uploading_files.

**Comment by eeshadutta** [comment]
@srish thanks for the review! I will work on the remaining sections.
 main.jpeg is a screenshot I took to show the working of the tool. I'll try uploading it through Wikimedia commons.

**Comment by eeshadutta** [comment]
@srish I have made the required changes : https://meta.wikimedia.org/wiki/User:Eeshadutta/Sandbox. The subpage is here: https://meta.wikimedia.org/wiki/WikiContrib/TechnicalDetails
I have linked the subpage in the 'See Also' section.
Please review. Thanks!

**Comment by srish** [comment]
@eeshadutta Hi! I am taking a quick look at your page. Suggesting a few changes:
* Add only one screenshot (put a thumbnail border to it with a title), probably this one https://commons.wikimedia.org/wiki/File:Visualize1.jpg. It should be placed on the right side and the size of the image should be small. Looking at the image, the quality seems bad. You should take a new screenshot and save it in a png format and then re-upload.
* Also, rename the page https://meta.wikimedia.org/wiki/WikiContrib/TechnicalDetails to "Proposed implementation" with "P" caps, "i" small and there should be space between the two words.
   * Also, add a "DRAFT" category on this page, so that it looks like this page is not polished
   * Remove the Contact sections as it is going to be on the homepage.

**Comment by eeshadutta** [comment]
@srish done!

**Comment by srish** [comment]
@eeshadutta Just made small edits, you can now move your changes from https://meta.wikimedia.org/wiki/User:Eeshadutta/Sandbox to https://meta.wikimedia.org/wiki/WikiContrib. Thank you :)

**Comment by eeshadutta** [comment]
@srish I have edited https://meta.wikimedia.org/wiki/WikiContrib as mentioned.
