### ISSUE TITLE
Design a logo for WikiContrib project

### ISSUE THREAD

**Issue by srish** [wikimedia/WikiContrib#69]
> Note: This task is reserved for Google Code-in students. Please do not claim this task. 

WikiContrib tool provides a visualization within a specified time range of users' contributions to Wikimedia projects on Phabricator and Gerrit. You can play around with it here: https://tools.wmflabs.org/wikicontrib/. 

Design a fun logo following the tips-and-tricks below: 
* Submit the design as a vector [SVG](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics) file which can be resized without pixelation. Do not include any [bitmap image](https://en.wikipedia.org/wiki/Raster_graphics) (e.g. JPG, PNG, BMP, GIF, etc.) in your design. 
* Submissions must be [free](https://en.wikipedia.org/wiki/Free_content) and must not include any non-free materials. Please mention the [license under which you put the file](https://commons.wikimedia.org/wiki/Commons:Licensing) (e.g. [Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0)). You can not re-use another author's design work, except for when it is under a [CC-0](https://creativecommons.org/publicdomain/zero/1.0/legalcode) license.
* Upload your final design in a comment on the Google Code-in task.

The best design will become the logo of the WikiContrib project, and we might ask you later to upload it to [Wikimedia Commons](https://commons.wikimedia.org/wiki/Main_Page) :)

**Comment by srish** [comment]
Imported here https://codein.withgoogle.com/dashboard/tasks/5708807938768896/.

**Comment by zoranzoki21** [comment]
Hi, URL for me shows 404.

**Comment by srish** [comment]
@zoranzoki21 thank you for reporting this! We are investigating...In the meantime, if you would like to know what the visualization generated by the tool looks like, take a look at this image here https://srishtisethi.com/img/project-gallery/wikicontrib.png

**Comment by rammanoj** [comment]
@zoranzoki21 There was an error in travis ci script. I was trying to resolve it for the past two days. Everytime a person makes a commit to the server, it gets deployed and because of the error in script, deployment used to be aborted in middle. I fixed it today. You can check it now.

**Comment by subscriptshoe9** [comment]
Here is the logo from GCI : https://commons.wikimedia.org/wiki/File:WikiContrib_Logo_2019-12-21.svg

**Comment by srish** [comment]
Thanks to @tuxology for iterating on the design of logo contributed by @subscriptshoe9. Here it is: https://commons.wikimedia.org/w/index.php?title=File:WikiContrib_Logo_2019-12-21.svg and we are now using it :-)
