### ISSUE TITLE
Add icon of corresponding platform entities in user activity on specific date

### ISSUE THREAD

**Issue by rammanoj** [wikimedia/WikiContrib#71]
> Note: This task is reserved for Google Code-in students. Please do not claim this task.

On clicking the User activity on a specific date, the list of tasks on that specific date are being displayed.
Example:
![image](https://user-images.githubusercontent.com/21082378/69396081-22eb4e80-0d07-11ea-8645-a720f26590ae.png)

I guess the design need to be updated, maybe an icon can be added for each of them alike:
![image](https://user-images.githubusercontent.com/21082378/69399718-37cede80-0d15-11ea-94d3-edde5e538bd4.png)

The icon signifies the platform of the commit. 

The icon can have the following properties:

1. OnClick redirect to corresponding platform.
2. Onhover show a popup (maybe black transparent one) at top center with content like "Phabticator" or "Gerrit" based on the platform.

 However it is open for new ideas :)

**Comment by rammanoj** [comment]
Imported to https://codein.withgoogle.com/dashboard/tasks/4823572363608064/

**Comment by urbanecm** [comment]
Hello, I've removed the "beginner task" checkbox from your GCI task. This task is a proper coding task, rather than a "getting started" type of tasks, like "go to IRC and say hi" or "learn how to use Gerrit". Otherwise, looks good, published.

**Comment by srish** [comment]
(fixed by @ajuancer via https://github.com/wikimedia/WikiContrib/pull/104)
