### ISSUE TITLE
Remove outlines on focusing the inputs

### ISSUE THREAD

**Issue by rammanoj** [wikimedia/WikiContrib#73]
> Note: This task is reserved for Google Code-in students. Please do not claim this task.

Upon focusing the inputs, there are blue borders being appeared.
![image](https://user-images.githubusercontent.com/21082378/69397248-84adb780-0d0b-11ea-9436-5460160f7d99.png)

This is not the fault of the tool, as far as I know, it is nature of the web browser. I can reproduce this in chrome and brave. But I could not see it in firefox. 

I haven't tested it with safari (But I guess safari also show the borders).

The border appears weird with the current UI and it does not appear in all the browsers. So, I guess  removing them will be better option...

For reference: https://medium.com/@ricardozea/how-to-remove-the-blue-border-outline-in-chrome-safari-and-dotted-line-in-firefox-edge-fe5e2155d44c

**Comment by rammanoj** [comment]
Imported to https://codein.withgoogle.com/dashboard/tasks/5310433011957760/

**Comment by urbanecm** [comment]
Unmarked as beginner and published.
