### ISSUE TITLE
Add hovering affects to commits on specific date

### ISSUE THREAD

**Issue by rammanoj** [wikimedia/WikiContrib#74]
> Note: This task is reserved for Google Code-in students. Please do not claim this task.

Add hovering affect to the commits on specific date. It can look like: (fourth commit in the image).
![helo](https://user-images.githubusercontent.com/21082378/69400311-34d4ed80-0d17-11ea-95fd-98f8bd90c810.png)

Presently, all the commits are displayed in the cards with a shadow as shown in the above figure. [Hover property](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover) can be added to each of them to improve User experience a bit (by differentiating the currently hovered card with other ones). In general sense, shadow will be added on hover(in most of the websites), but we already have shadow for the cards over here. So, following two things can be done to add the hovering affect:

1. Remove the box shadow of the hovered card.
2. Add the border to hovered card

**Comment by rammanoj** [comment]
Imported to https://codein.withgoogle.com/dashboard/tasks/5404943666642944/

**Comment by rammanoj** [comment]
Your CSS code also add hovering affects to the card that are loading... Please check it once and make another patch to it.

**Comment by ShcherbaDev** [comment]
Please check my pull request #92

**Comment by srish** [comment]
Fixed by @ShcherbaDev via #92 and #89
