### ISSUE TITLE
Rename "PORT"  to "DB_PORT"

### ISSUE THREAD

**Issue by rammanoj** [wikimedia/WikiContrib#75]
> Note: This task is reserved for Google Code-in students. Please do not claim this task.

In .env.example there is a variable named **PORT**. It provide the details of the database port through which the current backend server can be connected to database server. 

In toolforge, on hosting this tool with the variable named **PORT** in environment file, the tool is not responding to any requests. The exact reason for it is still unknown (There might be some internal configuration issues). So rename the variable **PORT** to **DB_PORT** in .env.example file.

On changing the variable **PORT** to **DB_PORT**, you also need to replace **env('PORT')** in settings.py file.

**Comment by rammanoj** [comment]
Imported to https://codein.withgoogle.com/dashboard/tasks/6221921776041984/

**Comment by X3NOSIZ** [comment]
Check pull request #79
